// <auto-generated />
using System;
using E_Commerce_T.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_T.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924040259_extendUserPAsswordLength")]
    partial class extendUserPAsswordLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Address", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("postalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Brand", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Cart", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.CartItems", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("cartId")
                        .HasColumnType("bigint");

                    b.Property<long>("productVariantId")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cartId");

                    b.HasIndex("productVariantId");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Category", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("parentCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("parentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            name = "Clothes"
                        },
                        new
                        {
                            id = 2L,
                            name = "Shoes"
                        });
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Color", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("hexCode")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Order", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("orderedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("AddressId");

                    b.HasIndex("userId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.OrderItems", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("orderId")
                        .HasColumnType("bigint");

                    b.Property<long>("productVariantId")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("orderId");

                    b.HasIndex("productVariantId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("brandId")
                        .HasColumnType("bigint");

                    b.Property<long>("categoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.HasIndex("categoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.ProductVariant", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("colorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("discountEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("discountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("discountStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("productId")
                        .HasColumnType("bigint");

                    b.Property<long>("quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("sizeId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("colorId");

                    b.HasIndex("productId");

                    b.HasIndex("sizeId");

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Size", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Address", b =>
                {
                    b.HasOne("E_Commerce_T.Data.Entities.User", "user")
                        .WithOne("address")
                        .HasForeignKey("E_Commerce_T.Data.Entities.Address", "userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Cart", b =>
                {
                    b.HasOne("E_Commerce_T.Data.Entities.User", "user")
                        .WithOne("cart")
                        .HasForeignKey("E_Commerce_T.Data.Entities.Cart", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.CartItems", b =>
                {
                    b.HasOne("E_Commerce_T.Data.Entities.Cart", "cart")
                        .WithMany("cartItems")
                        .HasForeignKey("cartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_T.Data.Entities.ProductVariant", "productVariant")
                        .WithMany()
                        .HasForeignKey("productVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("productVariant");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Category", b =>
                {
                    b.HasOne("E_Commerce_T.Data.Entities.Category", "parentCategory")
                        .WithMany("subCategories")
                        .HasForeignKey("parentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("parentCategory");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Order", b =>
                {
                    b.HasOne("E_Commerce_T.Data.Entities.Address", "address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Commerce_T.Data.Entities.User", "user")
                        .WithMany("orders")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("address");

                    b.Navigation("user");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.OrderItems", b =>
                {
                    b.HasOne("E_Commerce_T.Data.Entities.Order", "order")
                        .WithMany("orderItems")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_T.Data.Entities.ProductVariant", "productVariant")
                        .WithMany()
                        .HasForeignKey("productVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("productVariant");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Product", b =>
                {
                    b.HasOne("E_Commerce_T.Data.Entities.Brand", "brand")
                        .WithMany("products")
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_T.Data.Entities.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");

                    b.Navigation("category");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.ProductVariant", b =>
                {
                    b.HasOne("E_Commerce_T.Data.Entities.Color", "color")
                        .WithMany("products")
                        .HasForeignKey("colorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_T.Data.Entities.Product", "product")
                        .WithMany("productVariants")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_T.Data.Entities.Size", "size")
                        .WithMany("products")
                        .HasForeignKey("sizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("color");

                    b.Navigation("product");

                    b.Navigation("size");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Brand", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Cart", b =>
                {
                    b.Navigation("cartItems");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Category", b =>
                {
                    b.Navigation("products");

                    b.Navigation("subCategories");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Color", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Order", b =>
                {
                    b.Navigation("orderItems");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Product", b =>
                {
                    b.Navigation("productVariants");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.Size", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("E_Commerce_T.Data.Entities.User", b =>
                {
                    b.Navigation("address")
                        .IsRequired();

                    b.Navigation("cart")
                        .IsRequired();

                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
